executable     = task.sh
arguments      = "$(PROCESS) 4 $(ClusterId)"
error          = logs/gridtune_array.$(CLUSTER).$(PROCESS).out
output         = logs/gridtune_array.$(CLUSTER).$(PROCESS).output
log            = logs/gridtune_array.$(CLUSTER).$(PROCESS).log

## GPU
request_gpus   = 1
request_memory = 80G
requirements   = (TARGET.GPUs_DeviceName =?= "Tesla V100-PCIE-32GB") || (TARGET.GPUs_DeviceName =?= "NVIDIA RTX A6000")
#requirements  = TARGET.GPUs_DeviceName =?= "Tesla P100-PCIE-12GB"
+MaxRuntime    = 86400

## CPU
#request_gpus   = 0
#request_cpus   = 4
#request_memory = 4G
#+MaxRuntime    = 8600

queue 4

# Array job with a job queue size of (4), which is the
# total number of jobs, which run either in parallel or not
# (depending on cluster resources)