classes: [0]             #  Which classes to use in the regularization

losstype: 'MINE_EMA'     # 'MINE' or 'MINE_EMA'
alpha:  0.01             #  Exponential Moving Average (EMA) coupling parameter
ma_eT:  1.0              #  EMA starting value

x_index: [0]             #  Variable indices (can contain several)
y_index: [1]

num_iter: 1000

mlp_dim: [64, 64]
dropout: 0.01
noise_std: 0.025
lr: 1.0e-3
weight_decay: 1.0e-5
